### ISSUE TITLE
The download link seems broken

### ISSUE THREAD

**Issue by caoyunkang** [featw/hpatches#6]
Thanks for your share. And I want to download the 'HPatches full sequences'. But the link [HPatches full sequences]('http://icvl.ee.ic.ac.uk/vbalnt/hpatches/hpatches-sequences-release.tar.gz') seems broken. Can you share the new link with me please?

**Comment by neon5d** [comment]
Indeed, the server was down.

**Comment by caoyunkang** [comment]
Could you please send the HPatches full sequences to me? My email is: 1076504979@qq.com.

**Comment by water-wave** [comment]
i need the dataset,please

**Comment by vbalnt** [comment]
Hi everyone, the server is down today, we are working on this and it should be back up as soon as possible.

**Comment by vbalnt** [comment]
Website is up again. Thanks
